################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../StdPeriphDriver/src/misc.c \
../StdPeriphDriver/src/stm32f4xx_adc.c \
../StdPeriphDriver/src/stm32f4xx_can.c \
../StdPeriphDriver/src/stm32f4xx_cec.c \
../StdPeriphDriver/src/stm32f4xx_crc.c \
../StdPeriphDriver/src/stm32f4xx_cryp.c \
../StdPeriphDriver/src/stm32f4xx_cryp_aes.c \
../StdPeriphDriver/src/stm32f4xx_cryp_des.c \
../StdPeriphDriver/src/stm32f4xx_cryp_tdes.c \
../StdPeriphDriver/src/stm32f4xx_dac.c \
../StdPeriphDriver/src/stm32f4xx_dbgmcu.c \
../StdPeriphDriver/src/stm32f4xx_dcmi.c \
../StdPeriphDriver/src/stm32f4xx_dfsdm.c \
../StdPeriphDriver/src/stm32f4xx_dma.c \
../StdPeriphDriver/src/stm32f4xx_dma2d.c \
../StdPeriphDriver/src/stm32f4xx_dsi.c \
../StdPeriphDriver/src/stm32f4xx_exti.c \
../StdPeriphDriver/src/stm32f4xx_flash.c \
../StdPeriphDriver/src/stm32f4xx_flash_ramfunc.c \
../StdPeriphDriver/src/stm32f4xx_fmc.c \
../StdPeriphDriver/src/stm32f4xx_fmip2c.c \
../StdPeriphDriver/src/stm32f4xx_fsmc.c \
../StdPeriphDriver/src/stm32f4xx_gpio.c \
../StdPeriphDriver/src/stm32f4xx_hash.c \
../StdPeriphDriver/src/stm32f4xx_hash_md5.c \
../StdPeriphDriver/src/stm32f4xx_hash_sha1.c \
../StdPeriphDriver/src/stm32f4xx_i2c.c \
../StdPeriphDriver/src/stm32f4xx_iwdg.c \
../StdPeriphDriver/src/stm32f4xx_lptim.c \
../StdPeriphDriver/src/stm32f4xx_ltdc.c \
../StdPeriphDriver/src/stm32f4xx_pwr.c \
../StdPeriphDriver/src/stm32f4xx_qspi.c \
../StdPeriphDriver/src/stm32f4xx_rcc.c \
../StdPeriphDriver/src/stm32f4xx_rng.c \
../StdPeriphDriver/src/stm32f4xx_rtc.c \
../StdPeriphDriver/src/stm32f4xx_sai.c \
../StdPeriphDriver/src/stm32f4xx_sdio.c \
../StdPeriphDriver/src/stm32f4xx_spdifrx.c \
../StdPeriphDriver/src/stm32f4xx_spi.c \
../StdPeriphDriver/src/stm32f4xx_syscfg.c \
../StdPeriphDriver/src/stm32f4xx_tim.c \
../StdPeriphDriver/src/stm32f4xx_usart.c \
../StdPeriphDriver/src/stm32f4xx_wwdg.c 

OBJS += \
./StdPeriphDriver/src/misc.o \
./StdPeriphDriver/src/stm32f4xx_adc.o \
./StdPeriphDriver/src/stm32f4xx_can.o \
./StdPeriphDriver/src/stm32f4xx_cec.o \
./StdPeriphDriver/src/stm32f4xx_crc.o \
./StdPeriphDriver/src/stm32f4xx_cryp.o \
./StdPeriphDriver/src/stm32f4xx_cryp_aes.o \
./StdPeriphDriver/src/stm32f4xx_cryp_des.o \
./StdPeriphDriver/src/stm32f4xx_cryp_tdes.o \
./StdPeriphDriver/src/stm32f4xx_dac.o \
./StdPeriphDriver/src/stm32f4xx_dbgmcu.o \
./StdPeriphDriver/src/stm32f4xx_dcmi.o \
./StdPeriphDriver/src/stm32f4xx_dfsdm.o \
./StdPeriphDriver/src/stm32f4xx_dma.o \
./StdPeriphDriver/src/stm32f4xx_dma2d.o \
./StdPeriphDriver/src/stm32f4xx_dsi.o \
./StdPeriphDriver/src/stm32f4xx_exti.o \
./StdPeriphDriver/src/stm32f4xx_flash.o \
./StdPeriphDriver/src/stm32f4xx_flash_ramfunc.o \
./StdPeriphDriver/src/stm32f4xx_fmc.o \
./StdPeriphDriver/src/stm32f4xx_fmip2c.o \
./StdPeriphDriver/src/stm32f4xx_fsmc.o \
./StdPeriphDriver/src/stm32f4xx_gpio.o \
./StdPeriphDriver/src/stm32f4xx_hash.o \
./StdPeriphDriver/src/stm32f4xx_hash_md5.o \
./StdPeriphDriver/src/stm32f4xx_hash_sha1.o \
./StdPeriphDriver/src/stm32f4xx_i2c.o \
./StdPeriphDriver/src/stm32f4xx_iwdg.o \
./StdPeriphDriver/src/stm32f4xx_lptim.o \
./StdPeriphDriver/src/stm32f4xx_ltdc.o \
./StdPeriphDriver/src/stm32f4xx_pwr.o \
./StdPeriphDriver/src/stm32f4xx_qspi.o \
./StdPeriphDriver/src/stm32f4xx_rcc.o \
./StdPeriphDriver/src/stm32f4xx_rng.o \
./StdPeriphDriver/src/stm32f4xx_rtc.o \
./StdPeriphDriver/src/stm32f4xx_sai.o \
./StdPeriphDriver/src/stm32f4xx_sdio.o \
./StdPeriphDriver/src/stm32f4xx_spdifrx.o \
./StdPeriphDriver/src/stm32f4xx_spi.o \
./StdPeriphDriver/src/stm32f4xx_syscfg.o \
./StdPeriphDriver/src/stm32f4xx_tim.o \
./StdPeriphDriver/src/stm32f4xx_usart.o \
./StdPeriphDriver/src/stm32f4xx_wwdg.o 

C_DEPS += \
./StdPeriphDriver/src/misc.d \
./StdPeriphDriver/src/stm32f4xx_adc.d \
./StdPeriphDriver/src/stm32f4xx_can.d \
./StdPeriphDriver/src/stm32f4xx_cec.d \
./StdPeriphDriver/src/stm32f4xx_crc.d \
./StdPeriphDriver/src/stm32f4xx_cryp.d \
./StdPeriphDriver/src/stm32f4xx_cryp_aes.d \
./StdPeriphDriver/src/stm32f4xx_cryp_des.d \
./StdPeriphDriver/src/stm32f4xx_cryp_tdes.d \
./StdPeriphDriver/src/stm32f4xx_dac.d \
./StdPeriphDriver/src/stm32f4xx_dbgmcu.d \
./StdPeriphDriver/src/stm32f4xx_dcmi.d \
./StdPeriphDriver/src/stm32f4xx_dfsdm.d \
./StdPeriphDriver/src/stm32f4xx_dma.d \
./StdPeriphDriver/src/stm32f4xx_dma2d.d \
./StdPeriphDriver/src/stm32f4xx_dsi.d \
./StdPeriphDriver/src/stm32f4xx_exti.d \
./StdPeriphDriver/src/stm32f4xx_flash.d \
./StdPeriphDriver/src/stm32f4xx_flash_ramfunc.d \
./StdPeriphDriver/src/stm32f4xx_fmc.d \
./StdPeriphDriver/src/stm32f4xx_fmip2c.d \
./StdPeriphDriver/src/stm32f4xx_fsmc.d \
./StdPeriphDriver/src/stm32f4xx_gpio.d \
./StdPeriphDriver/src/stm32f4xx_hash.d \
./StdPeriphDriver/src/stm32f4xx_hash_md5.d \
./StdPeriphDriver/src/stm32f4xx_hash_sha1.d \
./StdPeriphDriver/src/stm32f4xx_i2c.d \
./StdPeriphDriver/src/stm32f4xx_iwdg.d \
./StdPeriphDriver/src/stm32f4xx_lptim.d \
./StdPeriphDriver/src/stm32f4xx_ltdc.d \
./StdPeriphDriver/src/stm32f4xx_pwr.d \
./StdPeriphDriver/src/stm32f4xx_qspi.d \
./StdPeriphDriver/src/stm32f4xx_rcc.d \
./StdPeriphDriver/src/stm32f4xx_rng.d \
./StdPeriphDriver/src/stm32f4xx_rtc.d \
./StdPeriphDriver/src/stm32f4xx_sai.d \
./StdPeriphDriver/src/stm32f4xx_sdio.d \
./StdPeriphDriver/src/stm32f4xx_spdifrx.d \
./StdPeriphDriver/src/stm32f4xx_spi.d \
./StdPeriphDriver/src/stm32f4xx_syscfg.d \
./StdPeriphDriver/src/stm32f4xx_tim.d \
./StdPeriphDriver/src/stm32f4xx_usart.d \
./StdPeriphDriver/src/stm32f4xx_wwdg.d 


# Each subdirectory must supply rules for building sources it contributes
StdPeriphDriver/src/misc.o: ../StdPeriphDriver/src/misc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/misc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_adc.o: ../StdPeriphDriver/src/stm32f4xx_adc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_adc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_can.o: ../StdPeriphDriver/src/stm32f4xx_can.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_can.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_cec.o: ../StdPeriphDriver/src/stm32f4xx_cec.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_cec.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_crc.o: ../StdPeriphDriver/src/stm32f4xx_crc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_crc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_cryp.o: ../StdPeriphDriver/src/stm32f4xx_cryp.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_cryp.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_cryp_aes.o: ../StdPeriphDriver/src/stm32f4xx_cryp_aes.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_cryp_aes.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_cryp_des.o: ../StdPeriphDriver/src/stm32f4xx_cryp_des.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_cryp_des.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_cryp_tdes.o: ../StdPeriphDriver/src/stm32f4xx_cryp_tdes.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_cryp_tdes.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_dac.o: ../StdPeriphDriver/src/stm32f4xx_dac.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_dac.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_dbgmcu.o: ../StdPeriphDriver/src/stm32f4xx_dbgmcu.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_dbgmcu.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_dcmi.o: ../StdPeriphDriver/src/stm32f4xx_dcmi.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_dcmi.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_dfsdm.o: ../StdPeriphDriver/src/stm32f4xx_dfsdm.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_dfsdm.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_dma.o: ../StdPeriphDriver/src/stm32f4xx_dma.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_dma.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_dma2d.o: ../StdPeriphDriver/src/stm32f4xx_dma2d.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_dma2d.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_dsi.o: ../StdPeriphDriver/src/stm32f4xx_dsi.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_dsi.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_exti.o: ../StdPeriphDriver/src/stm32f4xx_exti.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_exti.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_flash.o: ../StdPeriphDriver/src/stm32f4xx_flash.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_flash.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_flash_ramfunc.o: ../StdPeriphDriver/src/stm32f4xx_flash_ramfunc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_flash_ramfunc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_fmc.o: ../StdPeriphDriver/src/stm32f4xx_fmc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_fmc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_fmip2c.o: ../StdPeriphDriver/src/stm32f4xx_fmip2c.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_fmip2c.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_fsmc.o: ../StdPeriphDriver/src/stm32f4xx_fsmc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_fsmc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_gpio.o: ../StdPeriphDriver/src/stm32f4xx_gpio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_gpio.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_hash.o: ../StdPeriphDriver/src/stm32f4xx_hash.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_hash.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_hash_md5.o: ../StdPeriphDriver/src/stm32f4xx_hash_md5.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_hash_md5.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_hash_sha1.o: ../StdPeriphDriver/src/stm32f4xx_hash_sha1.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_hash_sha1.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_i2c.o: ../StdPeriphDriver/src/stm32f4xx_i2c.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_i2c.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_iwdg.o: ../StdPeriphDriver/src/stm32f4xx_iwdg.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_iwdg.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_lptim.o: ../StdPeriphDriver/src/stm32f4xx_lptim.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_lptim.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_ltdc.o: ../StdPeriphDriver/src/stm32f4xx_ltdc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_ltdc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_pwr.o: ../StdPeriphDriver/src/stm32f4xx_pwr.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_pwr.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_qspi.o: ../StdPeriphDriver/src/stm32f4xx_qspi.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_qspi.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_rcc.o: ../StdPeriphDriver/src/stm32f4xx_rcc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_rcc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_rng.o: ../StdPeriphDriver/src/stm32f4xx_rng.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_rng.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_rtc.o: ../StdPeriphDriver/src/stm32f4xx_rtc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_rtc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_sai.o: ../StdPeriphDriver/src/stm32f4xx_sai.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_sai.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_sdio.o: ../StdPeriphDriver/src/stm32f4xx_sdio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_sdio.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_spdifrx.o: ../StdPeriphDriver/src/stm32f4xx_spdifrx.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_spdifrx.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_spi.o: ../StdPeriphDriver/src/stm32f4xx_spi.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_spi.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_syscfg.o: ../StdPeriphDriver/src/stm32f4xx_syscfg.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_syscfg.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_tim.o: ../StdPeriphDriver/src/stm32f4xx_tim.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_tim.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_usart.o: ../StdPeriphDriver/src/stm32f4xx_usart.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_usart.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
StdPeriphDriver/src/stm32f4xx_wwdg.o: ../StdPeriphDriver/src/stm32f4xx_wwdg.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/core" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Config" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/portable/GCC/ARM_CM4F" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/ThirdParty/FreeRTOS/org/Source/include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/CMSIS/device" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/Include" -I"/home/irvin/STM32CubeIDE/workspace_1.1.0/STM32_Hello_World/StdPeriphDriver/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"StdPeriphDriver/src/stm32f4xx_wwdg.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

